### PR TITLE
Usability recommendation changes

### PR DESCRIPTION
**Pull request by ayaleloehr**
Proposed resolution to: #367

### CODE REVIEW

**Comment by SteffieP** [comment]
Morning everyone! The additional verbiage on the 'Choose a School' looks good. Can we allow the focus group to test with this change and see if there is confusion on how to search for a school? Thanks

**Comment by ayaleloehr** [comment]
@rickleegit i believe this was your change, but then I closed your PR for some reason and created a new one. What's the status here?  Should we merge?

**Comment by rickleegit** [comment]
No merge. Waiting on input from Stacey/Stakeholders.

**Comment by ayaleloehr** [comment]
OBE

**Pull request closed without merging**
