### PR TITLE
Add figaro to enable deployment

### PR DESCRIPTION
**Pull request by jkassemi**

### CODE REVIEW

**Comment by jkassemi** [comment]
Will wait for #395

**Comment by ayaleloehr** [comment]
@jkassemi How were environment variables being set up before?  This seems to only add Figaro but not remove anything else; can you provide context for why this is necessary?

**Comment by jkassemi** [comment]
This is popping up as a result of https://github.com/department-of-veterans-affairs/devops/pull/406.

They were originally configured directly with environment variables (my personal preference) but we just need to standardize on something that works.

**Comment by jkassemi** [comment]
Prefer to go with traditional ENV support.

**Pull request closed without merging**
