### PR TITLE
Fixing linting violations

### PR DESCRIPTION
**Pull request by knkski**

### CODE REVIEW

**Comment by saneshark** [comment]
@mphprogrammer Ken has added Jenkins integration + rubocop linting, etc to this repo. I will do a quick look over the rubocop changes, but could you please take a look as well sometime in the AM tomorrow so that we can try to get these changes merged.

**Comment by knkski** [comment]
@saneshark, @mphprogrammer: Anything holding this back, or can we merge this?

**Comment by mphprogrammer** [comment]
@knkski Nothing that I know of ... took a quick peek, but nothing leapt off the page.

**Comment by saneshark** [comment]
@knkski I don't really see any problem with this either, but I also don't see it as particularly pressing as most of our focus and efforts are now with the gibct-data-service and the vets-website changes that will replace this repo.

**Comment by saneshark** [comment]
Other than some kind of bug fix, I don't anticipate us really working in this repo very much moving forward.

**Comment by knkski** [comment]
Sure. I'll merge so that the Jenkins builds work, but won't do anything beyond that

**Pull request merged**
