### PR TITLE
Added utility links back in.

### PR DESCRIPTION
**Pull request by rickleegit**
Fixes this: https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/issues/249

@mphprogrammer 
screen shot 2016-02-08 at 4 00 43 pm
screen shot 2016-02-08 at 4 00 54 pm
screen shot 2016-02-08 at 4 01 01 pm

### CODE REVIEW

**Comment by emilyville** [comment]
@rickleegit a few comments!

- let's make "feedback" clearly distinguishable from user voice feedback. Feedback and who/what? If it's not different, can we should remove because right now users wouldn't know.

OR - better yet, can we consolidate and own  sending whatever feedback to the appropriate channels??

- and the same is true for accessibility - we have some accessibility content on vets.gov - where is this sending people and why do we think it's important here?

- also for any link that goes anywhere other than va.gov or stays on vets.gov please add the new window icon. (If it opens a mail to we might consider a mail icon... )

happy to discuss more, but want to make sure we're clear to users about where these things are going!

**Comment by saintsoup52** [comment]
The accessibility link was required for 508 purposes when we launched... if we can get rid of it now because it is somewhere else on the tool great.

As for the feedback... currently that is how VA EDU finds out there are issues with the tool, especially   from schools about data being displayed. The current vets.gov feedback is not accessible to VA EDU and not having regular access to that feedback would become a major source of frustration.

**Comment by rickleegit** [comment]
Patrick,

I think Emily is advocating making it more prominent and clearly distinguished from the user voice inputs and only removing it if that is impossible. 

We will work up a solution.

Thanks,

Rick

**Comment by emilyville** [comment]
Re:feedback link

I'm actually more advocating that we make it clearer where your feedback is going. We set a high bar for responding to all of our feedback and it is incorporated into our site. My concerns are 

- first and foremost: users don't know the difference between responding to ed vs vets.gov based on what we're showing them. This needs to be clear
- what is your sla for a response and your customer experience around it? It is like it takes you to a paragraph where it asks you to send an email or log in to... Somewhere... To provide feedback? It's that right?

**Comment by rickleegit** [comment]
Fair enough. Let me run this to ground.

**Pull request merged**
