### PR TITLE
Added a default ENV variable for SECRET_KEY_BASE

### PR DESCRIPTION
**Pull request by plusjeff**
Might fix the problem with Heroku clearing the production value of the secret_key_base value for production.

### CODE REVIEW

**Comment by mphprogrammer** [comment]
Weird, but I cannot see the link to heroku to check the deploy...

**Comment by plusjeff** [comment]
image

I botched the app.json file. I'll fix this next week.

**Comment by ayaleloehr** [comment]
@plusjeff please let me know if I should do work here to fix something or if this is no longer relevant.

**Comment by ayaleloehr** [comment]
Fixes Heroku review apps. TBR= @mphprogrammer and going to merge to see if this can fix the other branches as well.

**Pull request merged**
