### PR TITLE
report data inaccuracies mailto added

### PR DESCRIPTION
**Pull request by rickleegit**
@mphprogrammer: Can we please push this to staging and make sure that it also gets pushed to prod today?

Thanks!

screen shot 2016-02-11 at 6 16 18 am

### CODE REVIEW

**Comment by rickleegit** [comment]
@emilyville ^^

**Comment by emilyville** [comment]
@rickleegit are you asking for a review or just tagging me for awareness?

**Comment by rickleegit** [comment]
Awareness only.

**Comment by mphprogrammer** [comment]
This would undo PR 249 - EDU utility links.

**Pull request merged**
