### PR TITLE
usability reccos changes comp

### PR DESCRIPTION
**Pull request by rickleegit**
Proposed resolution to: 

https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/issues/367

### CODE REVIEW

**Comment by rickleegit** [comment]
@ayaleloehr @plusjeff: Little help. This build failed and I have no idea where to even begin diagnosing this issue. Clicked details but did not get any details that helped. 

screen shot 2016-05-23 at 2 08 39 pm

**Comment by rickleegit** [comment]
@ayaleloehr @plusjeff: Little help. This build failed and I have no idea where to even begin diagnosing this issue. Clicked details but did not get any details that helped.

screen shot 2016-05-23 at 2 19 59 pm

**Comment by rickleegit** [comment]
@staceylanger Having an issue with Heroku. Have asked Alex and Jeff for assistance. In the meantime, a screen cap:

screen shot 2016-05-23 at 2 28 56 pm

**Comment by ayaleloehr** [comment]
Not sure what's going on. Going to try closing this PR and creating a new one to see if that fixes it.

**Pull request closed without merging**
