### PR TITLE
Updating to va_common 0.4.0 and updating CSS for visual compat.

### PR DESCRIPTION
**Pull request by webinista**
- Changing p font-size to inherit.
- Adjusting font sizes, form input sizes for compat with USWDS.
- Adjusting search box, applinks font sizes.
- Adjusting footer layout and styles.
- Updating GIBCT home, search, profile pages with new title styles, breadcrumbs.
- Updating search, profile pages with new breadcrumbs.

Changed files

- Gemfile.lock
- app/assets/js/toggle-veterans-crisis-line.js
- app/assets/stylesheets/_scss/va-components/_gi.scss
- app/views/institutions/home.html.erb
- app/views/institutions/profile.html.erb
- app/views/institutions/search.html.erb
- app/assets/stylesheets/_scss/va-components/_gi-icons.scss
- app/assets/stylesheets/_scss/va-components/_gi-timeline.scss

Removing duplicate load of VA common CSS.

### CODE REVIEW

**Comment by ayaleloehr** [comment]
Main page looks great. Search page still has some issues however. This one is turning into a harder problem than originally thought, and the work will have to be replicated on VEC as well. cc @plusjeff for awareness. 

screen shot 2016-07-05 at 3 34 51 pm

**Comment by webinista** [comment]
Updated `nokogiri` to 1.6.8 as part of this PR since some security issues were causing the build to break. I can't tell whether we actually _need_ nokogiri 1.6.8 though. It's in `Gemfile.lock` but not `Gemfile`.

**Comment by ayaleloehr** [comment]
@webinista sorry this is turning into so much larger of a thing than it was originally thought. The breadcrumbs look great, but there are a few other things that I think got messed up with the styles.  

When doing a search, the text in the dropdown is now white, so you can't read it:
screen shot 2016-07-12 at 7 51 03 pm

Then also when on a school profile page, some of the text/images look off:
screen shot 2016-07-12 at 7 51 48 pm

**Comment by webinista** [comment]
Blocks:
- department-of-veterans-affairs/vets-website#2414
- department-of-veterans-affairs/vets-website#2422

**Comment by ayaleloehr** [comment]
Differences I notice now between these GI Bill changes and the vets-website header/footer changes found [here](https://vets-website-pr-2422.herokuapp.com/education/gi-bill/): 

Footer on GI Bill still has the lightbulb in the bottom right corner, but the vets-website changes do not. (Spacing in footer is also larger in GI Bill, but this is minor). 

GI Bill
screen shot 2016-07-13 at 8 23 27 pm

Vets-website
screen shot 2016-07-13 at 8 23 42 pm



Headers are slightly different, although I'm struggling to pinpoint exactly what change one would make to make them more similar, so maybe this isn't a big enough issue to have to change @webinista ?  The difference that is more likely to matter is that vets-website has the breadcrumb root as "home" whereas GI Bill has it as "Education Benefits". 

GI Bill:
screen shot 2016-07-13 at 8 23 04 pm

Vets-website
screen shot 2016-07-13 at 8 27 10 pm

**Comment by webinista** [comment]
I have no idea where that UserVoice bubble is coming from. I do not think that should delay us, since this issue is blocking other issues.

**Comment by ayaleloehr** [comment]
LGTM!  Thanks @webinista this is great!

**Pull request merged**
